id: I6C483647
default_language: bo
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:27:28.769753
last_modified: 2023-01-04 11:27:28.769767
source_metadata:
  collections:
  - Adzom Drukpa Series
  - Works of Tibetan Masters
bases:
  22F5:
    title: 'The Ambrosia of Blessings: A Prayer to the Vidyādhara of Unparalleled
      Kindness, Drodül Pawo Dorje'
    base_file: 22F5.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
